### ISSUE TITLE
WARNING: Clp had build errors

### ISSUE THREAD

**Issue by volker-raschek** [JuliaOpt/Clp.jl#43] opened 2018-10-18 12:10 UTC
I get the following error on my Arch Linux System.
Kernel: 4.18.12-arch1-1-ARCH
gfortan: GNU Fortran (GCC) 8.2.1 20180831
julia: 0.6.4
clp: 0.4

```julia
julia> using Clp # Solver -> Lineare Optimierung
INFO: Precompiling module Clp.
ERROR: LoadError: LoadError: Clp not properly installed. Please run Pkg.build("Clp")
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/markus/.local/share/julia/v0.6/Clp/src/ClpCInterface.jl, in expression starting on line 188
while loading /home/markus/.local/share/julia/v0.6/Clp/src/Clp.jl, in expression starting on line 10
ERROR: Failed to precompile Clp to /home/markus/.local/share/julia/lib/v0.6/Clp.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] eval(::Module, ::Any) at ./boot.jl:235
```

```julia
julia> Pkg.build("Clp")
INFO: Building Clp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   172    0   172    0     0    287      0 --:--:-- --:--:-- --:--:--   287
100   622    0   622    0     0    817      0 --:--:-- --:--:-- --:--:--   817
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com
=====================================================[ ERROR: Clp ]======================================================

LoadError: failed process: Process(`curl -L -f -o build_COINBLASBuilder.v1.4.6.jl https://github.com/juan-pablo-vielma/COINBLASBuilder/releases/download/v1.4.6-beta2/build_COINBLASBuilder.v1.4.6.jl`, ProcessExited(6)) [6]
while loading /home/markus/.local/share/julia/v0.6/Clp/deps/build.jl, in expression starting on line 38

=========================================================================================================================

====================================================[ BUILD ERRORS ]=====================================================

WARNING: Clp had build errors.

 - packages with build errors remain installed in /home/markus/.local/share/julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Clp")`
 - build a single package by running its `deps/build.jl` script

=========================================================================================================================

```

I've compiled julia from the source code to get the version 0.6.4. I need the version 0.6.4 for my study.
Did I need some more additional packages or is this a Clp error? Please can anyone fix this bug?

Volker

**Comment by blegat** [comment] 2018-10-18 12:33
The error is `curl: (6) Could not resolve host: github-production-release-asset-2e65be.s3.amazonaws.com`. Maybe the server was temporarily down. I have just tried and it works:
```
$ curl -L -f -o build_COINBLASBuilder.v1.4.6.jl https://github.com/juan-pablo-vielma/COINBLASBuilder/releases/download/v1.4.6-beta2/build_COINBLASBuilder.v1.4.6.jl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   172    0   172    0     0    186      0 --:--:-- --:--:-- --:--:--   186
100   622    0   622    0     0    506      0 --:--:--  0:00:01 --:--:--  607k
100  3355  100  3355    0     0   1951      0  0:00:01  0:00:01 --:--:--  1951
```
can you check again ?

**Comment by volker-raschek** [comment] 2018-10-18 12:42
I've tried it with curl and it works fine: 
```bash
markus@markus-nb:~$ curl -L -f -o build_COINBLASBuilder.v1.4.6.jl https://github.com/juan-pablo-vielma/COINBLASBuilder/releases/download/v1.4.6-beta2/build_COINBLASBuilder.v1.4.6.jl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   172    0   172    0     0    285      0 --:--:-- --:--:-- --:--:--   285
100   622    0   622    0     0    784      0 --:--:-- --:--:-- --:--:--   784
100  3355  100  3355    0     0   2205      0  0:00:01  0:00:01 --:--:--  2205
markus@markus-nb:~$ echo $?
0
```

When I want to build clp again, I get the same error:
```julia
julia> Pkg.build("Clp")
INFO: Building Clp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   172    0   172    0     0    129      0 --:--:--  0:00:01 --:--:--   129
100   622    0   622    0     0    413      0 --:--:--  0:00:01 --:--:--   413
100  3355  100  3355    0     0   1416      0  0:00:02  0:00:02 --:--:-- 30225
=====================================================[ ERROR: Clp ]======================================================

LoadError: LoadError: BinaryProvider.LibraryProduct(nothing, String["libcoinblas"], Symbol(""), "Prefix(/home/markus/.local/share/julia/v0.6/Clp/deps/usr)") is not satisfied, cannot generate deps.jl!
while loading /home/markus/.local/share/julia/v0.6/Clp/deps/build_COINBLASBuilder.v1.4.6.jl, in expression starting on line 45
while loading /home/markus/.local/share/julia/v0.6/Clp/deps/build.jl, in expression starting on line 38

=========================================================================================================================

====================================================[ BUILD ERRORS ]=====================================================

WARNING: Clp had build errors.

 - packages with build errors remain installed in /home/markus/.local/share/julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Clp")`
 - build a single package by running its `deps/build.jl` script

=========================================================================================================================
```

How can I build clp manually when I download the file via curl?

**Comment by blegat** [comment] 2018-10-18 13:12
Now you get a different error which is a duplicate of https://github.com/JuliaOpt/Clp.jl/issues/38

**Closed by blegat** 2018-10-18 13:12 UTC
